# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disein.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 600)
        MainWindow.setMinimumSize(QtCore.QSize(740, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_1 = QtWidgets.QWidget(self.centralwidget)
        self.widget_1.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_1.setObjectName("widget_1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_1)
        self.gridLayout.setContentsMargins(5, 4, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.start_check_GPON = QtWidgets.QPushButton(self.widget_1)
        self.start_check_GPON.setObjectName("start_check_GPON")
        self.gridLayout.addWidget(self.start_check_GPON, 1, 2, 1, 1)
        self.ipAddressEdit = QtWidgets.QLineEdit(self.widget_1)
        self.ipAddressEdit.setMinimumSize(QtCore.QSize(90, 0))
        self.ipAddressEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ipAddressEdit.setText("")
        self.ipAddressEdit.setObjectName("ipAddressEdit")
        self.gridLayout.addWidget(self.ipAddressEdit, 0, 1, 1, 1)
        self.portEdit = QtWidgets.QLineEdit(self.widget_1)
        self.portEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.portEdit.setText("")
        self.portEdit.setObjectName("portEdit")
        self.gridLayout.addWidget(self.portEdit, 0, 3, 1, 1)
        self.start_check_EPON = QtWidgets.QPushButton(self.widget_1)
        self.start_check_EPON.setMinimumSize(QtCore.QSize(105, 0))
        self.start_check_EPON.setObjectName("start_check_EPON")
        self.gridLayout.addWidget(self.start_check_EPON, 1, 4, 1, 1)
        self.port_label = QtWidgets.QLabel(self.widget_1)
        self.port_label.setTextFormat(QtCore.Qt.AutoText)
        self.port_label.setScaledContents(False)
        self.port_label.setWordWrap(True)
        self.port_label.setObjectName("port_label")
        self.gridLayout.addWidget(self.port_label, 0, 2, 1, 1)
        self.interfice_label = QtWidgets.QLabel(self.widget_1)
        self.interfice_label.setWordWrap(True)
        self.interfice_label.setObjectName("interfice_label")
        self.gridLayout.addWidget(self.interfice_label, 0, 4, 1, 1)
        self.ipAddressLBL = QtWidgets.QLabel(self.widget_1)
        self.ipAddressLBL.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ipAddressLBL.setFont(font)
        self.ipAddressLBL.setWordWrap(True)
        self.ipAddressLBL.setObjectName("ipAddressLBL")
        self.gridLayout.addWidget(self.ipAddressLBL, 0, 0, 1, 1)
        self.interficeEdit = QtWidgets.QLineEdit(self.widget_1)
        self.interficeEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.interficeEdit.setObjectName("interficeEdit")
        self.gridLayout.addWidget(self.interficeEdit, 0, 5, 1, 1)
        self.Huawei_BTN = QtWidgets.QPushButton(self.widget_1)
        self.Huawei_BTN.setObjectName("Huawei_BTN")
        self.gridLayout.addWidget(self.Huawei_BTN, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.resultEdit = QtWidgets.QTextEdit(self.widget)
        self.resultEdit.setObjectName("resultEdit")
        self.horizontalLayout.addWidget(self.resultEdit)
        self.result2Edit = QtWidgets.QTextEdit(self.widget)
        self.result2Edit.setObjectName("result2Edit")
        self.horizontalLayout.addWidget(self.result2Edit)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_check_GPON.setText(_translate("MainWindow", "GPON"))
        self.start_check_EPON.setText(_translate("MainWindow", "EPON"))
        self.port_label.setText(_translate("MainWindow", "Порт коммутатора"))
        self.interfice_label.setText(_translate("MainWindow", "Интерфейс абонента"))
        self.ipAddressLBL.setText(_translate("MainWindow", "Введите IP коммутатора"))
        self.Huawei_BTN.setText(_translate("MainWindow", "Huawei Коммут-р"))
